Python 3.11.3 (tags/v3.11.3:f3909b8, Apr  4 2023, 23:49:59) [MSC v.1934 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license()" for more information.

== RESTART: C:\Users\HP\AppData\Local\Programs\Python\Python311\screen_pet.py ==
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\screen_pet.py", line 69, in show_happy
    c.intemconfigure(mouth_happy, state=NORMAL)
    ^^^^^^^^^^^^^^^^
AttributeError: 'Canvas' object has no attribute 'intemconfigure'
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\screen_pet.py", line 69, in show_happy
    c.intemconfigure(mouth_happy, state=NORMAL)
    ^^^^^^^^^^^^^^^^
AttributeError: 'Canvas' object has no attribute 'intemconfigure'
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\screen_pet.py", line 69, in show_happy
    c.intemconfigure(mouth_happy, state=NORMAL)
    ^^^^^^^^^^^^^^^^
AttributeError: 'Canvas' object has no attribute 'intemconfigure'
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\screen_pet.py", line 69, in show_happy
    c.intemconfigure(mouth_happy, state=NORMAL)
    ^^^^^^^^^^^^^^^^
AttributeError: 'Canvas' object has no attribute 'intemconfigure'
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\screen_pet.py", line 69, in show_happy
    c.intemconfigure(mouth_happy, state=NORMAL)
    ^^^^^^^^^^^^^^^^
AttributeError: 'Canvas' object has no attribute 'intemconfigure'
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\screen_pet.py", line 69, in show_happy
    c.intemconfigure(mouth_happy, state=NORMAL)
    ^^^^^^^^^^^^^^^^
AttributeError: 'Canvas' object has no attribute 'intemconfigure'
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\screen_pet.py", line 69, in show_happy
    c.intemconfigure(mouth_happy, state=NORMAL)
    ^^^^^^^^^^^^^^^^
AttributeError: 'Canvas' object has no attribute 'intemconfigure'
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\screen_pet.py", line 69, in show_happy
    c.intemconfigure(mouth_happy, state=NORMAL)
    ^^^^^^^^^^^^^^^^
AttributeError: 'Canvas' object has no attribute 'intemconfigure'
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\screen_pet.py", line 69, in show_happy
    c.intemconfigure(mouth_happy, state=NORMAL)
    ^^^^^^^^^^^^^^^^
AttributeError: 'Canvas' object has no attribute 'intemconfigure'
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\screen_pet.py", line 69, in show_happy
    c.intemconfigure(mouth_happy, state=NORMAL)
    ^^^^^^^^^^^^^^^^
AttributeError: 'Canvas' object has no attribute 'intemconfigure'
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\screen_pet.py", line 69, in show_happy
    c.intemconfigure(mouth_happy, state=NORMAL)
    ^^^^^^^^^^^^^^^^
AttributeError: 'Canvas' object has no attribute 'intemconfigure'
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\screen_pet.py", line 69, in show_happy
    c.intemconfigure(mouth_happy, state=NORMAL)
    ^^^^^^^^^^^^^^^^
AttributeError: 'Canvas' object has no attribute 'intemconfigure'
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\screen_pet.py", line 69, in show_happy
    c.intemconfigure(mouth_happy, state=NORMAL)
    ^^^^^^^^^^^^^^^^
AttributeError: 'Canvas' object has no attribute 'intemconfigure'
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\screen_pet.py", line 69, in show_happy
    c.intemconfigure(mouth_happy, state=NORMAL)
    ^^^^^^^^^^^^^^^^
AttributeError: 'Canvas' object has no attribute 'intemconfigure'
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\screen_pet.py", line 69, in show_happy
    c.intemconfigure(mouth_happy, state=NORMAL)
    ^^^^^^^^^^^^^^^^
AttributeError: 'Canvas' object has no attribute 'intemconfigure'
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\screen_pet.py", line 69, in show_happy
    c.intemconfigure(mouth_happy, state=NORMAL)
    ^^^^^^^^^^^^^^^^
AttributeError: 'Canvas' object has no attribute 'intemconfigure'
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\screen_pet.py", line 69, in show_happy
    c.intemconfigure(mouth_happy, state=NORMAL)
    ^^^^^^^^^^^^^^^^
AttributeError: 'Canvas' object has no attribute 'intemconfigure'
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\screen_pet.py", line 69, in show_happy
    c.intemconfigure(mouth_happy, state=NORMAL)
    ^^^^^^^^^^^^^^^^
AttributeError: 'Canvas' object has no attribute 'intemconfigure'
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\screen_pet.py", line 69, in show_happy
    c.intemconfigure(mouth_happy, state=NORMAL)
    ^^^^^^^^^^^^^^^^
AttributeError: 'Canvas' object has no attribute 'intemconfigure'
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\screen_pet.py", line 69, in show_happy
    c.intemconfigure(mouth_happy, state=NORMAL)
    ^^^^^^^^^^^^^^^^
AttributeError: 'Canvas' object has no attribute 'intemconfigure'
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\screen_pet.py", line 69, in show_happy
    c.intemconfigure(mouth_happy, state=NORMAL)
    ^^^^^^^^^^^^^^^^
AttributeError: 'Canvas' object has no attribute 'intemconfigure'
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\screen_pet.py", line 69, in show_happy
    c.intemconfigure(mouth_happy, state=NORMAL)
    ^^^^^^^^^^^^^^^^
AttributeError: 'Canvas' object has no attribute 'intemconfigure'
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\screen_pet.py", line 69, in show_happy
    c.intemconfigure(mouth_happy, state=NORMAL)
    ^^^^^^^^^^^^^^^^
AttributeError: 'Canvas' object has no attribute 'intemconfigure'
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\screen_pet.py", line 69, in show_happy
    c.intemconfigure(mouth_happy, state=NORMAL)
    ^^^^^^^^^^^^^^^^
AttributeError: 'Canvas' object has no attribute 'intemconfigure'
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\screen_pet.py", line 69, in show_happy
    c.intemconfigure(mouth_happy, state=NORMAL)
    ^^^^^^^^^^^^^^^^
AttributeError: 'Canvas' object has no attribute 'intemconfigure'
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\screen_pet.py", line 69, in show_happy
    c.intemconfigure(mouth_happy, state=NORMAL)
    ^^^^^^^^^^^^^^^^
AttributeError: 'Canvas' object has no attribute 'intemconfigure'
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\screen_pet.py", line 69, in show_happy
    c.intemconfigure(mouth_happy, state=NORMAL)
    ^^^^^^^^^^^^^^^^
AttributeError: 'Canvas' object has no attribute 'intemconfigure'
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\screen_pet.py", line 69, in show_happy
    c.intemconfigure(mouth_happy, state=NORMAL)
    ^^^^^^^^^^^^^^^^
AttributeError: 'Canvas' object has no attribute 'intemconfigure'
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\screen_pet.py", line 69, in show_happy
    c.intemconfigure(mouth_happy, state=NORMAL)
    ^^^^^^^^^^^^^^^^
AttributeError: 'Canvas' object has no attribute 'intemconfigure'
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\screen_pet.py", line 69, in show_happy
    c.intemconfigure(mouth_happy, state=NORMAL)
    ^^^^^^^^^^^^^^^^
AttributeError: 'Canvas' object has no attribute 'intemconfigure'
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\screen_pet.py", line 69, in show_happy
    c.intemconfigure(mouth_happy, state=NORMAL)
    ^^^^^^^^^^^^^^^^
AttributeError: 'Canvas' object has no attribute 'intemconfigure'

== RESTART: C:\Users\HP\AppData\Local\Programs\Python\Python311\screen_pet.py ==
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\screen_pet.py", line 69, in show_happy
    c.intemconfigure(mouth_happy, state=NORMAL)
    ^^^^^^^^^^^^^^^^
AttributeError: 'Canvas' object has no attribute 'intemconfigure'
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\screen_pet.py", line 69, in show_happy
    c.intemconfigure(mouth_happy, state=NORMAL)
    ^^^^^^^^^^^^^^^^
AttributeError: 'Canvas' object has no attribute 'intemconfigure'
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\screen_pet.py", line 69, in show_happy
    c.intemconfigure(mouth_happy, state=NORMAL)
    ^^^^^^^^^^^^^^^^
AttributeError: 'Canvas' object has no attribute 'intemconfigure'
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\screen_pet.py", line 69, in show_happy
    c.intemconfigure(mouth_happy, state=NORMAL)
    ^^^^^^^^^^^^^^^^
AttributeError: 'Canvas' object has no attribute 'intemconfigure'

== RESTART: C:\Users\HP\AppData\Local\Programs\Python\Python311\screen_pet.py ==
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\screen_pet.py", line 69, in show_happy
    c.intemconfigure(mouth_happy, state=NORMAL)
    ^^^^^^^^^^^^^^^^
AttributeError: 'Canvas' object has no attribute 'intemconfigure'
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\screen_pet.py", line 69, in show_happy
    c.intemconfigure(mouth_happy, state=NORMAL)
    ^^^^^^^^^^^^^^^^
AttributeError: 'Canvas' object has no attribute 'intemconfigure'
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\screen_pet.py", line 69, in show_happy
    c.intemconfigure(mouth_happy, state=NORMAL)
    ^^^^^^^^^^^^^^^^
AttributeError: 'Canvas' object has no attribute 'intemconfigure'
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\screen_pet.py", line 69, in show_happy
    c.intemconfigure(mouth_happy, state=NORMAL)
    ^^^^^^^^^^^^^^^^
AttributeError: 'Canvas' object has no attribute 'intemconfigure'
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\screen_pet.py", line 69, in show_happy
    c.intemconfigure(mouth_happy, state=NORMAL)
    ^^^^^^^^^^^^^^^^
AttributeError: 'Canvas' object has no attribute 'intemconfigure'
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\screen_pet.py", line 69, in show_happy
    c.intemconfigure(mouth_happy, state=NORMAL)
    ^^^^^^^^^^^^^^^^
AttributeError: 'Canvas' object has no attribute 'intemconfigure'
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\screen_pet.py", line 69, in show_happy
    c.intemconfigure(mouth_happy, state=NORMAL)
    ^^^^^^^^^^^^^^^^
AttributeError: 'Canvas' object has no attribute 'intemconfigure'
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\screen_pet.py", line 69, in show_happy
    c.intemconfigure(mouth_happy, state=NORMAL)
    ^^^^^^^^^^^^^^^^
AttributeError: 'Canvas' object has no attribute 'intemconfigure'
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\screen_pet.py", line 69, in show_happy
    c.intemconfigure(mouth_happy, state=NORMAL)
    ^^^^^^^^^^^^^^^^
AttributeError: 'Canvas' object has no attribute 'intemconfigure'
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\screen_pet.py", line 69, in show_happy
    c.intemconfigure(mouth_happy, state=NORMAL)
    ^^^^^^^^^^^^^^^^
AttributeError: 'Canvas' object has no attribute 'intemconfigure'
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\screen_pet.py", line 69, in show_happy
    c.intemconfigure(mouth_happy, state=NORMAL)
    ^^^^^^^^^^^^^^^^
AttributeError: 'Canvas' object has no attribute 'intemconfigure'

======================================= RESTART: C:\Users\HP\AppData\Local\Programs\Python\Python311\screen_pet.py ======================================
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\screen_pet.py", line 70, in show_happy
    c.itemconfigure(mouth_normal, state=HIDDEN)
                    ^^^^^^^^^^^^
NameError: name 'mouth_normal' is not defined
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\screen_pet.py", line 70, in show_happy
    c.itemconfigure(mouth_normal, state=HIDDEN)
                    ^^^^^^^^^^^^
NameError: name 'mouth_normal' is not defined
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\screen_pet.py", line 70, in show_happy
    c.itemconfigure(mouth_normal, state=HIDDEN)
                    ^^^^^^^^^^^^
NameError: name 'mouth_normal' is not defined
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\screen_pet.py", line 70, in show_happy
    c.itemconfigure(mouth_normal, state=HIDDEN)
                    ^^^^^^^^^^^^
NameError: name 'mouth_normal' is not defined
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\screen_pet.py", line 70, in show_happy
    c.itemconfigure(mouth_normal, state=HIDDEN)
                    ^^^^^^^^^^^^
NameError: name 'mouth_normal' is not defined
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\screen_pet.py", line 70, in show_happy
    c.itemconfigure(mouth_normal, state=HIDDEN)
                    ^^^^^^^^^^^^
NameError: name 'mouth_normal' is not defined
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\screen_pet.py", line 70, in show_happy
    c.itemconfigure(mouth_normal, state=HIDDEN)
                    ^^^^^^^^^^^^
NameError: name 'mouth_normal' is not defined
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\screen_pet.py", line 70, in show_happy
    c.itemconfigure(mouth_normal, state=HIDDEN)
                    ^^^^^^^^^^^^
NameError: name 'mouth_normal' is not defined

======================================= RESTART: C:\Users\HP\AppData\Local\Programs\Python\Python311\screen_pet.py ======================================
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\screen_pet.py", line 70, in show_happy
    c.itemconfigure(mouth_normal, state=NORMAL)
                    ^^^^^^^^^^^^
NameError: name 'mouth_normal' is not defined
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\screen_pet.py", line 70, in show_happy
    c.itemconfigure(mouth_normal, state=NORMAL)
                    ^^^^^^^^^^^^
NameError: name 'mouth_normal' is not defined
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\screen_pet.py", line 70, in show_happy
    c.itemconfigure(mouth_normal, state=NORMAL)
                    ^^^^^^^^^^^^
NameError: name 'mouth_normal' is not defined
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\screen_pet.py", line 70, in show_happy
    c.itemconfigure(mouth_normal, state=NORMAL)
                    ^^^^^^^^^^^^
NameError: name 'mouth_normal' is not defined
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\screen_pet.py", line 70, in show_happy
    c.itemconfigure(mouth_normal, state=NORMAL)
                    ^^^^^^^^^^^^
NameError: name 'mouth_normal' is not defined
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\screen_pet.py", line 70, in show_happy
    c.itemconfigure(mouth_normal, state=NORMAL)
                    ^^^^^^^^^^^^
NameError: name 'mouth_normal' is not defined
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\screen_pet.py", line 70, in show_happy
    c.itemconfigure(mouth_normal, state=NORMAL)
                    ^^^^^^^^^^^^
NameError: name 'mouth_normal' is not defined
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\screen_pet.py", line 70, in show_happy
    c.itemconfigure(mouth_normal, state=NORMAL)
                    ^^^^^^^^^^^^
NameError: name 'mouth_normal' is not defined
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\screen_pet.py", line 70, in show_happy
    c.itemconfigure(mouth_normal, state=NORMAL)
                    ^^^^^^^^^^^^
NameError: name 'mouth_normal' is not defined
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\screen_pet.py", line 70, in show_happy
    c.itemconfigure(mouth_normal, state=NORMAL)
                    ^^^^^^^^^^^^
NameError: name 'mouth_normal' is not defined
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\screen_pet.py", line 70, in show_happy
    c.itemconfigure(mouth_normal, state=NORMAL)
                    ^^^^^^^^^^^^
NameError: name 'mouth_normal' is not defined
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\screen_pet.py", line 70, in show_happy
    c.itemconfigure(mouth_normal, state=NORMAL)
                    ^^^^^^^^^^^^
NameError: name 'mouth_normal' is not defined
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\screen_pet.py", line 70, in show_happy
    c.itemconfigure(mouth_normal, state=NORMAL)
                    ^^^^^^^^^^^^
NameError: name 'mouth_normal' is not defined
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\screen_pet.py", line 70, in show_happy
    c.itemconfigure(mouth_normal, state=NORMAL)
                    ^^^^^^^^^^^^
NameError: name 'mouth_normal' is not defined
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\screen_pet.py", line 70, in show_happy
    c.itemconfigure(mouth_normal, state=NORMAL)
                    ^^^^^^^^^^^^
NameError: name 'mouth_normal' is not defined
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\screen_pet.py", line 70, in show_happy
    c.itemconfigure(mouth_normal, state=NORMAL)
                    ^^^^^^^^^^^^
NameError: name 'mouth_normal' is not defined
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\screen_pet.py", line 70, in show_happy
    c.itemconfigure(mouth_normal, state=NORMAL)
                    ^^^^^^^^^^^^
NameError: name 'mouth_normal' is not defined
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\screen_pet.py", line 70, in show_happy
    c.itemconfigure(mouth_normal, state=NORMAL)
                    ^^^^^^^^^^^^
NameError: name 'mouth_normal' is not defined
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\screen_pet.py", line 70, in show_happy
    c.itemconfigure(mouth_normal, state=NORMAL)
                    ^^^^^^^^^^^^
NameError: name 'mouth_normal' is not defined
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\screen_pet.py", line 70, in show_happy
    c.itemconfigure(mouth_normal, state=NORMAL)
                    ^^^^^^^^^^^^
NameError: name 'mouth_normal' is not defined
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\screen_pet.py", line 70, in show_happy
    c.itemconfigure(mouth_normal, state=NORMAL)
                    ^^^^^^^^^^^^
NameError: name 'mouth_normal' is not defined
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\screen_pet.py", line 70, in show_happy
    c.itemconfigure(mouth_normal, state=NORMAL)
                    ^^^^^^^^^^^^
NameError: name 'mouth_normal' is not defined
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\screen_pet.py", line 70, in show_happy
    c.itemconfigure(mouth_normal, state=NORMAL)
                    ^^^^^^^^^^^^
NameError: name 'mouth_normal' is not defined
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\screen_pet.py", line 70, in show_happy
    c.itemconfigure(mouth_normal, state=NORMAL)
                    ^^^^^^^^^^^^
NameError: name 'mouth_normal' is not defined
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\screen_pet.py", line 70, in show_happy
    c.itemconfigure(mouth_normal, state=NORMAL)
                    ^^^^^^^^^^^^
NameError: name 'mouth_normal' is not defined
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\screen_pet.py", line 70, in show_happy
    c.itemconfigure(mouth_normal, state=NORMAL)
                    ^^^^^^^^^^^^
NameError: name 'mouth_normal' is not defined
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\screen_pet.py", line 70, in show_happy
    c.itemconfigure(mouth_normal, state=NORMAL)
                    ^^^^^^^^^^^^
NameError: name 'mouth_normal' is not defined
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\screen_pet.py", line 70, in show_happy
    c.itemconfigure(mouth_normal, state=NORMAL)
                    ^^^^^^^^^^^^
NameError: name 'mouth_normal' is not defined
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\screen_pet.py", line 70, in show_happy
    c.itemconfigure(mouth_normal, state=NORMAL)
                    ^^^^^^^^^^^^
NameError: name 'mouth_normal' is not defined
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\screen_pet.py", line 70, in show_happy
    c.itemconfigure(mouth_normal, state=NORMAL)
                    ^^^^^^^^^^^^
NameError: name 'mouth_normal' is not defined
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\screen_pet.py", line 70, in show_happy
    c.itemconfigure(mouth_normal, state=NORMAL)
                    ^^^^^^^^^^^^
NameError: name 'mouth_normal' is not defined
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\screen_pet.py", line 70, in show_happy
    c.itemconfigure(mouth_normal, state=NORMAL)
                    ^^^^^^^^^^^^
NameError: name 'mouth_normal' is not defined
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\screen_pet.py", line 70, in show_happy
    c.itemconfigure(mouth_normal, state=NORMAL)
                    ^^^^^^^^^^^^
NameError: name 'mouth_normal' is not defined
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\screen_pet.py", line 70, in show_happy
    c.itemconfigure(mouth_normal, state=NORMAL)
                    ^^^^^^^^^^^^
NameError: name 'mouth_normal' is not defined
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\screen_pet.py", line 70, in show_happy
    c.itemconfigure(mouth_normal, state=NORMAL)
                    ^^^^^^^^^^^^
NameError: name 'mouth_normal' is not defined
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\screen_pet.py", line 70, in show_happy
    c.itemconfigure(mouth_normal, state=NORMAL)
                    ^^^^^^^^^^^^
NameError: name 'mouth_normal' is not defined
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\screen_pet.py", line 70, in show_happy
    c.itemconfigure(mouth_normal, state=NORMAL)
                    ^^^^^^^^^^^^
NameError: name 'mouth_normal' is not defined
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\screen_pet.py", line 70, in show_happy
    c.itemconfigure(mouth_normal, state=NORMAL)
                    ^^^^^^^^^^^^
NameError: name 'mouth_normal' is not defined
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\screen_pet.py", line 70, in show_happy
    c.itemconfigure(mouth_normal, state=NORMAL)
                    ^^^^^^^^^^^^
NameError: name 'mouth_normal' is not defined
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\screen_pet.py", line 70, in show_happy
    c.itemconfigure(mouth_normal, state=NORMAL)
                    ^^^^^^^^^^^^
NameError: name 'mouth_normal' is not defined
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\screen_pet.py", line 70, in show_happy
    c.itemconfigure(mouth_normal, state=NORMAL)
                    ^^^^^^^^^^^^
NameError: name 'mouth_normal' is not defined
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\screen_pet.py", line 70, in show_happy
    c.itemconfigure(mouth_normal, state=NORMAL)
                    ^^^^^^^^^^^^
NameError: name 'mouth_normal' is not defined
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\screen_pet.py", line 70, in show_happy
    c.itemconfigure(mouth_normal, state=NORMAL)
                    ^^^^^^^^^^^^
NameError: name 'mouth_normal' is not defined
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\screen_pet.py", line 70, in show_happy
    c.itemconfigure(mouth_normal, state=NORMAL)
                    ^^^^^^^^^^^^
NameError: name 'mouth_normal' is not defined
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\screen_pet.py", line 70, in show_happy
    c.itemconfigure(mouth_normal, state=NORMAL)
                    ^^^^^^^^^^^^
NameError: name 'mouth_normal' is not defined
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\screen_pet.py", line 70, in show_happy
    c.itemconfigure(mouth_normal, state=NORMAL)
                    ^^^^^^^^^^^^
NameError: name 'mouth_normal' is not defined
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\screen_pet.py", line 70, in show_happy
    c.itemconfigure(mouth_normal, state=NORMAL)
                    ^^^^^^^^^^^^
NameError: name 'mouth_normal' is not defined
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\screen_pet.py", line 70, in show_happy
    c.itemconfigure(mouth_normal, state=NORMAL)
                    ^^^^^^^^^^^^
NameError: name 'mouth_normal' is not defined
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\screen_pet.py", line 70, in show_happy
    c.itemconfigure(mouth_normal, state=NORMAL)
                    ^^^^^^^^^^^^
NameError: name 'mouth_normal' is not defined
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\screen_pet.py", line 70, in show_happy
    c.itemconfigure(mouth_normal, state=NORMAL)
                    ^^^^^^^^^^^^
NameError: name 'mouth_normal' is not defined
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\screen_pet.py", line 70, in show_happy
    c.itemconfigure(mouth_normal, state=NORMAL)
                    ^^^^^^^^^^^^
NameError: name 'mouth_normal' is not defined
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\screen_pet.py", line 70, in show_happy
    c.itemconfigure(mouth_normal, state=NORMAL)
                    ^^^^^^^^^^^^
NameError: name 'mouth_normal' is not defined
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\screen_pet.py", line 70, in show_happy
    c.itemconfigure(mouth_normal, state=NORMAL)
                    ^^^^^^^^^^^^
NameError: name 'mouth_normal' is not defined
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\screen_pet.py", line 70, in show_happy
    c.itemconfigure(mouth_normal, state=NORMAL)
                    ^^^^^^^^^^^^
NameError: name 'mouth_normal' is not defined
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\screen_pet.py", line 70, in show_happy
    c.itemconfigure(mouth_normal, state=NORMAL)
                    ^^^^^^^^^^^^
NameError: name 'mouth_normal' is not defined
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\screen_pet.py", line 70, in show_happy
    c.itemconfigure(mouth_normal, state=NORMAL)
                    ^^^^^^^^^^^^
NameError: name 'mouth_normal' is not defined
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\screen_pet.py", line 70, in show_happy
    c.itemconfigure(mouth_normal, state=NORMAL)
                    ^^^^^^^^^^^^
NameError: name 'mouth_normal' is not defined
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\screen_pet.py", line 70, in show_happy
    c.itemconfigure(mouth_normal, state=NORMAL)
                    ^^^^^^^^^^^^
NameError: name 'mouth_normal' is not defined
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\screen_pet.py", line 70, in show_happy
    c.itemconfigure(mouth_normal, state=NORMAL)
                    ^^^^^^^^^^^^
NameError: name 'mouth_normal' is not defined
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\screen_pet.py", line 70, in show_happy
    c.itemconfigure(mouth_normal, state=NORMAL)
                    ^^^^^^^^^^^^
NameError: name 'mouth_normal' is not defined
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\screen_pet.py", line 70, in show_happy
    c.itemconfigure(mouth_normal, state=NORMAL)
                    ^^^^^^^^^^^^
NameError: name 'mouth_normal' is not defined
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\screen_pet.py", line 70, in show_happy
    c.itemconfigure(mouth_normal, state=NORMAL)
                    ^^^^^^^^^^^^
NameError: name 'mouth_normal' is not defined
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\screen_pet.py", line 70, in show_happy
    c.itemconfigure(mouth_normal, state=NORMAL)
                    ^^^^^^^^^^^^
NameError: name 'mouth_normal' is not defined
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\screen_pet.py", line 70, in show_happy
    c.itemconfigure(mouth_normal, state=NORMAL)
                    ^^^^^^^^^^^^
NameError: name 'mouth_normal' is not defined
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\screen_pet.py", line 70, in show_happy
    c.itemconfigure(mouth_normal, state=NORMAL)
                    ^^^^^^^^^^^^
NameError: name 'mouth_normal' is not defined
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\screen_pet.py", line 70, in show_happy
    c.itemconfigure(mouth_normal, state=NORMAL)
                    ^^^^^^^^^^^^
NameError: name 'mouth_normal' is not defined

======================================= RESTART: C:\Users\HP\AppData\Local\Programs\Python\Python311\screen_pet.py ======================================
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\screen_pet.py", line 70, in show_happy
    c.itemconfigure(mouth_normal, state=HIDDEN)
                    ^^^^^^^^^^^^
NameError: name 'mouth_normal' is not defined
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\screen_pet.py", line 70, in show_happy
    c.itemconfigure(mouth_normal, state=HIDDEN)
                    ^^^^^^^^^^^^
NameError: name 'mouth_normal' is not defined
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\screen_pet.py", line 70, in show_happy
    c.itemconfigure(mouth_normal, state=HIDDEN)
                    ^^^^^^^^^^^^
NameError: name 'mouth_normal' is not defined
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\screen_pet.py", line 70, in show_happy
    c.itemconfigure(mouth_normal, state=HIDDEN)
                    ^^^^^^^^^^^^
NameError: name 'mouth_normal' is not defined
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\screen_pet.py", line 70, in show_happy
    c.itemconfigure(mouth_normal, state=HIDDEN)
                    ^^^^^^^^^^^^
NameError: name 'mouth_normal' is not defined
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\screen_pet.py", line 70, in show_happy
    c.itemconfigure(mouth_normal, state=HIDDEN)
                    ^^^^^^^^^^^^
NameError: name 'mouth_normal' is not defined
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\screen_pet.py", line 70, in show_happy
    c.itemconfigure(mouth_normal, state=HIDDEN)
                    ^^^^^^^^^^^^
NameError: name 'mouth_normal' is not defined
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\screen_pet.py", line 70, in show_happy
    c.itemconfigure(mouth_normal, state=HIDDEN)
                    ^^^^^^^^^^^^
NameError: name 'mouth_normal' is not defined
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\screen_pet.py", line 70, in show_happy
    c.itemconfigure(mouth_normal, state=HIDDEN)
                    ^^^^^^^^^^^^
NameError: name 'mouth_normal' is not defined

======================================= RESTART: C:\Users\HP\AppData\Local\Programs\Python\Python311\screen_pet.py ======================================
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\screen_pet.py", line 70, in show_happy
    c.itemconfigure(mouth_normal, state=HIDDEN)
                    ^^^^^^^^^^^^
NameError: name 'mouth_normal' is not defined
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\screen_pet.py", line 70, in show_happy
    c.itemconfigure(mouth_normal, state=HIDDEN)
                    ^^^^^^^^^^^^
NameError: name 'mouth_normal' is not defined
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\screen_pet.py", line 70, in show_happy
    c.itemconfigure(mouth_normal, state=HIDDEN)
                    ^^^^^^^^^^^^
NameError: name 'mouth_normal' is not defined
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\screen_pet.py", line 70, in show_happy
    c.itemconfigure(mouth_normal, state=HIDDEN)
                    ^^^^^^^^^^^^
NameError: name 'mouth_normal' is not defined
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\screen_pet.py", line 70, in show_happy
    c.itemconfigure(mouth_normal, state=HIDDEN)
                    ^^^^^^^^^^^^
NameError: name 'mouth_normal' is not defined
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\screen_pet.py", line 70, in show_happy
    c.itemconfigure(mouth_normal, state=HIDDEN)
                    ^^^^^^^^^^^^
NameError: name 'mouth_normal' is not defined
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\screen_pet.py", line 70, in show_happy
    c.itemconfigure(mouth_normal, state=HIDDEN)
                    ^^^^^^^^^^^^
NameError: name 'mouth_normal' is not defined
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\screen_pet.py", line 70, in show_happy
    c.itemconfigure(mouth_normal, state=HIDDEN)
                    ^^^^^^^^^^^^
NameError: name 'mouth_normal' is not defined

======================================= RESTART: C:\Users\HP\AppData\Local\Programs\Python\Python311\screen_pet.py ======================================
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\screen_pet.py", line 70, in show_happy
    c.itemconfigure(mouth_normal, state=HIDDEN)
                    ^^^^^^^^^^^^
NameError: name 'mouth_normal' is not defined
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\screen_pet.py", line 70, in show_happy
    c.itemconfigure(mouth_normal, state=HIDDEN)
                    ^^^^^^^^^^^^
NameError: name 'mouth_normal' is not defined
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\screen_pet.py", line 70, in show_happy
    c.itemconfigure(mouth_normal, state=HIDDEN)
                    ^^^^^^^^^^^^
NameError: name 'mouth_normal' is not defined

======================================= RESTART: C:\Users\HP\AppData\Local\Programs\Python\Python311\screen_pet.py ======================================
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\screen_pet.py", line 70, in show_happy
    c.itemconfigure(mouth_normal, state=HIDDEN)
                    ^^^^^^^^^^^^
NameError: name 'mouth_normal' is not defined
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\screen_pet.py", line 70, in show_happy
    c.itemconfigure(mouth_normal, state=HIDDEN)
                    ^^^^^^^^^^^^
NameError: name 'mouth_normal' is not defined
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\screen_pet.py", line 70, in show_happy
    c.itemconfigure(mouth_normal, state=HIDDEN)
                    ^^^^^^^^^^^^
NameError: name 'mouth_normal' is not defined
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\screen_pet.py", line 70, in show_happy
    c.itemconfigure(mouth_normal, state=HIDDEN)
                    ^^^^^^^^^^^^
NameError: name 'mouth_normal' is not defined
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\screen_pet.py", line 70, in show_happy
    c.itemconfigure(mouth_normal, state=HIDDEN)
                    ^^^^^^^^^^^^
NameError: name 'mouth_normal' is not defined
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\screen_pet.py", line 70, in show_happy
    c.itemconfigure(mouth_normal, state=HIDDEN)
                    ^^^^^^^^^^^^
NameError: name 'mouth_normal' is not defined
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\screen_pet.py", line 70, in show_happy
    c.itemconfigure(mouth_normal, state=HIDDEN)
                    ^^^^^^^^^^^^
NameError: name 'mouth_normal' is not defined
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\screen_pet.py", line 70, in show_happy
    c.itemconfigure(mouth_normal, state=HIDDEN)
                    ^^^^^^^^^^^^
NameError: name 'mouth_normal' is not defined
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\screen_pet.py", line 70, in show_happy
    c.itemconfigure(mouth_normal, state=HIDDEN)
                    ^^^^^^^^^^^^
NameError: name 'mouth_normal' is not defined
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\screen_pet.py", line 70, in show_happy
    c.itemconfigure(mouth_normal, state=HIDDEN)
                    ^^^^^^^^^^^^
NameError: name 'mouth_normal' is not defined
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\screen_pet.py", line 70, in show_happy
    c.itemconfigure(mouth_normal, state=HIDDEN)
                    ^^^^^^^^^^^^
NameError: name 'mouth_normal' is not defined
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\screen_pet.py", line 70, in show_happy
    c.itemconfigure(mouth_normal, state=HIDDEN)
                    ^^^^^^^^^^^^
NameError: name 'mouth_normal' is not defined
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\screen_pet.py", line 70, in show_happy
    c.itemconfigure(mouth_normal, state=HIDDEN)
                    ^^^^^^^^^^^^
NameError: name 'mouth_normal' is not defined
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\screen_pet.py", line 70, in show_happy
    c.itemconfigure(mouth_normal, state=HIDDEN)
                    ^^^^^^^^^^^^
NameError: name 'mouth_normal' is not defined
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\screen_pet.py", line 70, in show_happy
    c.itemconfigure(mouth_normal, state=HIDDEN)
                    ^^^^^^^^^^^^
NameError: name 'mouth_normal' is not defined
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\screen_pet.py", line 70, in show_happy
    c.itemconfigure(mouth_normal, state=HIDDEN)
                    ^^^^^^^^^^^^
NameError: name 'mouth_normal' is not defined
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\screen_pet.py", line 70, in show_happy
    c.itemconfigure(mouth_normal, state=HIDDEN)
                    ^^^^^^^^^^^^
NameError: name 'mouth_normal' is not defined
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\screen_pet.py", line 70, in show_happy
    c.itemconfigure(mouth_normal, state=HIDDEN)
                    ^^^^^^^^^^^^
NameError: name 'mouth_normal' is not defined
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\screen_pet.py", line 70, in show_happy
    c.itemconfigure(mouth_normal, state=HIDDEN)
                    ^^^^^^^^^^^^
NameError: name 'mouth_normal' is not defined
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\screen_pet.py", line 70, in show_happy
    c.itemconfigure(mouth_normal, state=HIDDEN)
                    ^^^^^^^^^^^^
NameError: name 'mouth_normal' is not defined
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\screen_pet.py", line 70, in show_happy
    c.itemconfigure(mouth_normal, state=HIDDEN)
                    ^^^^^^^^^^^^
NameError: name 'mouth_normal' is not defined
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\screen_pet.py", line 70, in show_happy
    c.itemconfigure(mouth_normal, state=HIDDEN)
                    ^^^^^^^^^^^^
NameError: name 'mouth_normal' is not defined
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\screen_pet.py", line 70, in show_happy
    c.itemconfigure(mouth_normal, state=HIDDEN)
                    ^^^^^^^^^^^^
NameError: name 'mouth_normal' is not defined
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\screen_pet.py", line 70, in show_happy
    c.itemconfigure(mouth_normal, state=HIDDEN)
                    ^^^^^^^^^^^^
NameError: name 'mouth_normal' is not defined
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\screen_pet.py", line 70, in show_happy
    c.itemconfigure(mouth_normal, state=HIDDEN)
                    ^^^^^^^^^^^^
NameError: name 'mouth_normal' is not defined
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\screen_pet.py", line 70, in show_happy
    c.itemconfigure(mouth_normal, state=HIDDEN)
                    ^^^^^^^^^^^^
NameError: name 'mouth_normal' is not defined
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\screen_pet.py", line 70, in show_happy
    c.itemconfigure(mouth_normal, state=HIDDEN)
                    ^^^^^^^^^^^^
NameError: name 'mouth_normal' is not defined
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\screen_pet.py", line 70, in show_happy
    c.itemconfigure(mouth_normal, state=HIDDEN)
                    ^^^^^^^^^^^^
NameError: name 'mouth_normal' is not defined
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\screen_pet.py", line 70, in show_happy
    c.itemconfigure(mouth_normal, state=HIDDEN)
                    ^^^^^^^^^^^^
NameError: name 'mouth_normal' is not defined

======================================= RESTART: C:\Users\HP\AppData\Local\Programs\Python\Python311\screen_pet.py ======================================
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\screen_pet.py", line 70, in show_happy
    c.itemconfigure(mouth_normal, state=HIDDEN)
                    ^^^^^^^^^^^^
NameError: name 'mouth_normal' is not defined
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\screen_pet.py", line 70, in show_happy
    c.itemconfigure(mouth_normal, state=HIDDEN)
                    ^^^^^^^^^^^^
NameError: name 'mouth_normal' is not defined
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\screen_pet.py", line 70, in show_happy
    c.itemconfigure(mouth_normal, state=HIDDEN)
                    ^^^^^^^^^^^^
NameError: name 'mouth_normal' is not defined
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\screen_pet.py", line 70, in show_happy
    c.itemconfigure(mouth_normal, state=HIDDEN)
                    ^^^^^^^^^^^^
NameError: name 'mouth_normal' is not defined
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\screen_pet.py", line 70, in show_happy
    c.itemconfigure(mouth_normal, state=HIDDEN)
                    ^^^^^^^^^^^^
NameError: name 'mouth_normal' is not defined
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\screen_pet.py", line 70, in show_happy
    c.itemconfigure(mouth_normal, state=HIDDEN)
                    ^^^^^^^^^^^^
NameError: name 'mouth_normal' is not defined
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\screen_pet.py", line 70, in show_happy
    c.itemconfigure(mouth_normal, state=HIDDEN)
                    ^^^^^^^^^^^^
NameError: name 'mouth_normal' is not defined
